/**
 * Created by laic on 2016-12-21.
 */
public enum SIPEvent {

    SEND_INVITE,
    SEND_TRY,
    SEND_RINGING,
    SEND_ACK,
    SEND_BYE,
    SEND_OK,
    RECEIVE_INVITE,
    RECEIVE_TRY,
    RECEIVE_RINGING,
    RECEIVE_ACK,
    RECEIVE_BYE,
    SEND_KEEPALIVE,
    RECEIVE_OK,
    SEND_BUSY,
    SOCK_TIMEOUT, RECEIVE_BUSY, SEND_ERROR
}
